In [1]:
# run cell to install prokbert lib (if necessary)
# pip install git+https://github.com/nbrg-ppcu/prokbert.git --quiet

In [1]:
import os
import torch
import datasets
import pandas as pd
from sklearn.metrics import accuracy_score, f1_score, matthews_corrcoef, balanced_accuracy_score
from transformers import TrainingArguments, Trainer, DataCollatorWithPadding

from Bio import SeqIO
from Bio.Seq import Seq
from Bio.SeqRecord import SeqRecord

from prokbert.tokenizer import LCATokenizer
from prokbert.sequtils import load_contigs, segment_sequences
from prokbert.models import ProkBertForSequenceClassification

In [41]:
os.environ["WANDB_PROJECT"]="genome-network-pretraining"

In [3]:
num_cores = 8
batch_size = 16

base_dir = '/home/datasets/experiments/experiment-bioinfo/'

In [4]:
train_ds = datasets.load_dataset("neuralbioinfo/PhaStyle-SequenceDB", split="BACPHLIP_TRAINING")
test_ds  = datasets.load_dataset("neuralbioinfo/PhaStyle-SequenceDB", split="BACPHLIP_VALIDATION")

2026-10-08 14:15:18,005 - INFO - HTTP Request: HEAD https://huggingface.co/datasets/neuralbioinfo/PhaStyle-SequenceDB/resolve/main/README.md "HTTP/1.1 307 Temporary Redirect"
Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
2026-10-08 14:15:18,007 - WARNING - Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
2026-10-08 14:15:18,035 - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/datasets/neuralbioinfo/PhaStyle-SequenceDB/a7772eef14b1b056ee9b14448a71b8d182cfc4e2/README.md "HTTP/1.1 200 OK"
2026-10-08 14:15:18,175 - INFO - HTTP Request: HEAD https://huggingface.co/datasets/neuralbioinfo/PhaStyle-SequenceDB/resolve/a7772eef14b1b056ee9b14448a71b8d182cfc4e2/PhaStyle-SequenceDB.py "HTTP/1.1 404 Not Found"
2026-10-08 14:15:18,551 - INFO - HTTP Request: HEAD https://s3.amazonaws.com/datasets.huggingface.co/datasets/datasets/neuralbioinfo/PhaStyle-SequenceDB/neuralbioinfo/PhaStyle-SequenceDB.py "HTTP/1.1 404 Not Found"
2026-10-08 14:15:18,710 - INFO - HTTP Request: GET https://huggingface.co/api/datasets/neuralbioinfo/PhaStyle-SequenceDB/revision/a7772eef14b1b056ee9b14448a71b8d182cfc4e2 "HTTP/1.1 200 OK"
2026-10-08 14:15:18,849 - INFO - HTTP Request: HEAD https://huggingface.co/datasets/neuralbioinfo/PhaStyle-SequenceDB/resolve/a7772eef14b1b056ee9b14448a71b8d182cfc4e2/.huggingface.yaml "HTTP/1.1 404 Not Found"
2026-10-08 14:15:19,067 - INFO - HTTP Request: GET https://datasets-server.huggingface.co/info?dataset=neuralbioinfo/PhaStyle-SequenceDB "HTTP/1.1 200 OK"
2026-10-08 14:15:19,216 - INFO - HTTP Request: GET https://huggingface.co/api/datasets/neuralbioinfo/PhaStyle-SequenceDB/tree/a7772eef14b1b056ee9b14448a71b8d182cfc4e2/data?recursive=true&expand=false "HTTP/1.1 200 OK"
2026-10-08 14:15:19,357 - INFO - HTTP Request: GET https://huggingface.co/api/datasets/neuralbioinfo/PhaStyle-SequenceDB/tree/a7772eef14b1b056ee9b14448a71b8d182cfc4e2?recursive=false&expand=false "HTTP/1.1 200 OK"
2026-10-08 14:15:19,508 - INFO - HTTP Request: HEAD https://huggingface.co/datasets/neuralbioinfo/PhaStyle-SequenceDB/resolve/a7772eef14b1b056ee9b14448a71b8d182cfc4e2/dataset_infos.json "HTTP/1.1 404 Not Found"
2026-10-08 14:15:19,707 - INFO - HTTP Request: HEAD https://huggingface.co/datasets/neuralbioinfo/PhaStyle-SequenceDB/resolve/main/README.md "HTTP/1.1 307 Temporary Redirect"
2026-10-08 14:15:19,736 - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/datasets/neuralbioinfo/PhaStyle-SequenceDB/a7772eef14b1b056ee9b14448a71b8d182cfc4e2/README.md "HTTP/1.1 200 OK"
2026-10-08 14:15:19,878 - INFO - HTTP Request: HEAD https://huggingface.co/datasets/neuralbioinfo/PhaStyle-SequenceDB/resolve/a7772eef14b1b056ee9b14448a71b8d182cfc4e2/PhaStyle-SequenceDB.py "HTTP/1.1 404 Not Found"
2026-10-08 14:15:20,012 - INFO - HTTP Request: HEAD https://s3.amazonaws.com/datasets.huggingface.co/datasets/datasets/neuralbioinfo/PhaStyle-SequenceDB/neuralbioinfo/PhaStyle-SequenceDB.py "HTTP/1.1 404 Not Found"
2026-10-08 14:15:20,167 - INFO - HTTP Request: HEAD https://huggingface.co/datasets/neuralbioinfo/PhaStyle-SequenceDB/resolve/a7772eef14b1b056ee9b14448a71b8d182cfc4e2/.huggingface.yaml "HTTP/1.1 404 Not Found"
2026-10-08 14:15:20,314 - INFO - HTTP Request: GET https://datasets-server.huggingface.co/info?dataset=neuralbioinfo/PhaStyle-SequenceDB "HTTP/1.1 200 OK"
2026-10-08 14:15:20,461 - INFO - HTTP Request: HEAD https://huggingface.co/datasets/neuralbioinfo/PhaStyle-SequenceDB/resolve/a7772eef14b1b056ee9b14448a71b8d182cfc4e2/dataset_infos.json "HTTP/1.1 404 Not Found"

In [5]:
print(f"train examples: {len(train_ds)}, columns: {train_ds.column_names}")
print(f"test examples: {len(test_ds)}, columns: {test_ds.column_names}")

train examples: 1798, columns: ['sequence_id', 'dataset', 'class_label', 'y', 'source_fasta_id', 'orientation', 'test_fastaid', 'L_seq', 'source_description', 'Genome type', 'Family', 'subds_seqid', 'sequence', '__index_level_0__']
test examples: 316, columns: ['sequence_id', 'dataset', 'class_label', 'y', 'source_fasta_id', 'orientation', 'test_fastaid', 'L_seq', 'source_description', 'Genome type', 'Family', 'subds_seqid', 'sequence', '__index_level_0__']

In [6]:
# remove cols
cols = ["dataset", "class_label", "test_fastaid", "L_seq", 'source_description', 'Genome type', 'Family', 'subds_seqid', "__index_level_0__"]

train_ds = train_ds.remove_columns(cols)
test_ds = test_ds.remove_columns(cols)

In [7]:
# rename y to label
train_ds = train_ds.rename_column("y", "label")
train_ds = train_ds.rename_column("source_fasta_id", "fasta_id")
test_ds = test_ds.rename_column("y", "label")
test_ds = test_ds.rename_column("source_fasta_id", "fasta_id")

In [8]:
train_df = train_ds.to_pandas()
test_df = test_ds.to_pandas()

In [9]:
train_df.head()

,sequence_id,label,fasta_id,orientation,sequence
0,0,0,PHAA0000323,forward,TGCGGCCGCCCCATCCTGTACGGGTTTCCAAGTCGATCGGAGGGCA...
1,1,0,PHAA0000323,reverse,TAACCGACCGGTCAGGAAGGTACCCCTGGGGGGGTACTCCCCCTGG...
2,2,1,PHAA0000761,forward,ATGGCTTCGACTCAGACTCCAGCCGTCGGCAAGACCACGGCCATCG...
3,3,1,PHAA0000761,reverse,GGGCGCAGGATACCAGCAGGGTTGACTTACCCGACTCACTCGGGTA...
4,4,0,PHAA0000840,forward,TGCGGCTGAGCCATCGTGTACGGGTTTCCAAGTCCATCAGAGCCGG...

In [10]:
test_df.head()

,sequence_id,label,fasta_id,orientation,sequence
0,1798,1,PHAA0000415,forward,AATTTTCCTTATTAGGCCGCAAGGGCCTTCATAGTTTTAGCGATTT...
1,1799,1,PHAA0000415,reverse,ATGTACAATATTAAATGCCTGACCAAAAACGAACAAGCTGAAATTG...
2,1800,0,PHAA0000088,forward,GTTTCAACATGTCTAAGGATATGGTTTATCATTTTGAAAAATATAA...
3,1801,0,PHAA0000088,reverse,CATGAAGCATTAAAAACACAGAATTACCGAAGATCGTCCAAGAGCA...
4,1802,0,PHAA0000253,forward,GTTTCAACATGTCTAAGGATATGGTTTATCATTTTGAAAAATATAA...

In [11]:
def save_pandas_as_fasta(df: pd.DataFrame, file_path: str) -> None:
    records = []
    for _, row in df.iterrows():
        records.append(SeqRecord(
            Seq(row["sequence"]),
            id=str(row["fasta_id"]),
            description=f"empy description",
        ))
    SeqIO.write(records, file_path, "fasta")

In [12]:
train_save_path = f"{base_dir}/example-train-dataset/phastyle-sequencedb-bachlip-training.fasta"
test_save_path = f"{base_dir}/example-test-dataset/phastyle-sequencedb-bachlip-validation.fasta"

In [13]:
save_pandas_as_fasta(train_df, train_save_path)
save_pandas_as_fasta(test_df, test_save_path)

In [14]:
train_dataset = load_contigs(
    [train_save_path],
    IsAddHeader=True,
    adding_reverse_complement=False,
    AsDataFrame=True,
    to_uppercase=True,
    is_add_sequence_id=True,
)

2026-10-08 14:15:24,404 - INFO - Loading sequence data into memory!

In [15]:
train_dataset.head()

,sequence_id,fasta_id,description,source_file,sequence,orientation
0,0,PHAA0000323,PHAA0000323 empy description,/home/datasets/experiments/experiment-bioinfo/...,TGCGGCCGCCCCATCCTGTACGGGTTTCCAAGTCGATCGGAGGGCA...,forward
1,1,PHAA0000323,PHAA0000323 empy description,/home/datasets/experiments/experiment-bioinfo/...,TAACCGACCGGTCAGGAAGGTACCCCTGGGGGGGTACTCCCCCTGG...,forward
2,2,PHAA0000761,PHAA0000761 empy description,/home/datasets/experiments/experiment-bioinfo/...,ATGGCTTCGACTCAGACTCCAGCCGTCGGCAAGACCACGGCCATCG...,forward
3,3,PHAA0000761,PHAA0000761 empy description,/home/datasets/experiments/experiment-bioinfo/...,GGGCGCAGGATACCAGCAGGGTTGACTTACCCGACTCACTCGGGTA...,forward
4,4,PHAA0000840,PHAA0000840 empy description,/home/datasets/experiments/experiment-bioinfo/...,TGCGGCTGAGCCATCGTGTACGGGTTTCCAAGTCCATCAGAGCCGG...,forward

In [16]:
train_dataset[train_dataset["fasta_id"] == "PHAA0000323"]

,sequence_id,fasta_id,description,source_file,sequence,orientation
0,0,PHAA0000323,PHAA0000323 empy description,/home/datasets/experiments/experiment-bioinfo/...,TGCGGCCGCCCCATCCTGTACGGGTTTCCAAGTCGATCGGAGGGCA...,forward
1,1,PHAA0000323,PHAA0000323 empy description,/home/datasets/experiments/experiment-bioinfo/...,TAACCGACCGGTCAGGAAGGTACCCCTGGGGGGGTACTCCCCCTGG...,forward

In [17]:
labels = train_df[["fasta_id", "label"]].drop_duplicates()
train_dataset = train_dataset.merge(labels, on="fasta_id", how="left", validate="many_to_one")

In [18]:
train_dataset.head()

,sequence_id,fasta_id,description,source_file,sequence,orientation,label
0,0,PHAA0000323,PHAA0000323 empy description,/home/datasets/experiments/experiment-bioinfo/...,TGCGGCCGCCCCATCCTGTACGGGTTTCCAAGTCGATCGGAGGGCA...,forward,0
1,1,PHAA0000323,PHAA0000323 empy description,/home/datasets/experiments/experiment-bioinfo/...,TAACCGACCGGTCAGGAAGGTACCCCTGGGGGGGTACTCCCCCTGG...,forward,0
2,2,PHAA0000761,PHAA0000761 empy description,/home/datasets/experiments/experiment-bioinfo/...,ATGGCTTCGACTCAGACTCCAGCCGTCGGCAAGACCACGGCCATCG...,forward,1
3,3,PHAA0000761,PHAA0000761 empy description,/home/datasets/experiments/experiment-bioinfo/...,GGGCGCAGGATACCAGCAGGGTTGACTTACCCGACTCACTCGGGTA...,forward,1
4,4,PHAA0000840,PHAA0000840 empy description,/home/datasets/experiments/experiment-bioinfo/...,TGCGGCTGAGCCATCGTGTACGGGTTTCCAAGTCCATCAGAGCCGG...,forward,0

In [19]:
test_dataset = load_contigs(
    [test_save_path],
    IsAddHeader=True,
    adding_reverse_complement=False,
    AsDataFrame=True,
    to_uppercase=True,
    is_add_sequence_id=True,
)

2026-10-08 14:15:27,511 - INFO - Loading sequence data into memory!

In [20]:
test_dataset.head()

,sequence_id,fasta_id,description,source_file,sequence,orientation
0,0,PHAA0000415,PHAA0000415 empy description,/home/datasets/experiments/experiment-bioinfo/...,AATTTTCCTTATTAGGCCGCAAGGGCCTTCATAGTTTTAGCGATTT...,forward
1,1,PHAA0000415,PHAA0000415 empy description,/home/datasets/experiments/experiment-bioinfo/...,ATGTACAATATTAAATGCCTGACCAAAAACGAACAAGCTGAAATTG...,forward
2,2,PHAA0000088,PHAA0000088 empy description,/home/datasets/experiments/experiment-bioinfo/...,GTTTCAACATGTCTAAGGATATGGTTTATCATTTTGAAAAATATAA...,forward
3,3,PHAA0000088,PHAA0000088 empy description,/home/datasets/experiments/experiment-bioinfo/...,CATGAAGCATTAAAAACACAGAATTACCGAAGATCGTCCAAGAGCA...,forward
4,4,PHAA0000253,PHAA0000253 empy description,/home/datasets/experiments/experiment-bioinfo/...,GTTTCAACATGTCTAAGGATATGGTTTATCATTTTGAAAAATATAA...,forward

In [21]:
labels = test_df[["fasta_id", "label"]].drop_duplicates()
test_dataset = test_dataset.merge(labels, on="fasta_id", how="left", validate="many_to_one")

In [22]:
test_dataset.head()

,sequence_id,fasta_id,description,source_file,sequence,orientation,label
0,0,PHAA0000415,PHAA0000415 empy description,/home/datasets/experiments/experiment-bioinfo/...,AATTTTCCTTATTAGGCCGCAAGGGCCTTCATAGTTTTAGCGATTT...,forward,1
1,1,PHAA0000415,PHAA0000415 empy description,/home/datasets/experiments/experiment-bioinfo/...,ATGTACAATATTAAATGCCTGACCAAAAACGAACAAGCTGAAATTG...,forward,1
2,2,PHAA0000088,PHAA0000088 empy description,/home/datasets/experiments/experiment-bioinfo/...,GTTTCAACATGTCTAAGGATATGGTTTATCATTTTGAAAAATATAA...,forward,0
3,3,PHAA0000088,PHAA0000088 empy description,/home/datasets/experiments/experiment-bioinfo/...,CATGAAGCATTAAAAACACAGAATTACCGAAGATCGTCCAAGAGCA...,forward,0
4,4,PHAA0000253,PHAA0000253 empy description,/home/datasets/experiments/experiment-bioinfo/...,GTTTCAACATGTCTAAGGATATGGTTTATCATTTTGAAAAATATAA...,forward,0

In [23]:
# import importlib
# import prokbert.sequtils
# importlib.reload(prokbert.sequtils)
# from prokbert.sequtils import segment_sequences

segmentation_params = {
    "max_length": 2_000,
    "min_length": int(2_000 * 0.5),
    "type": "random",
    "coverage": 1
}
raw_segment_train_df = segment_sequences(train_dataset, segmentation_params, AsDataFrame=True)

2026-10-08 14:15:30,845 - INFO - Checking input DataFrame!
2026-10-08 14:15:30,847 - INFO - Checking input sequence_id is valid primary key in the DataFrame
2026-10-08 14:15:30,931 - INFO - Sampling 58341 segments from 1798 sequences.
2026-10-08 14:15:30,943 - INFO - Too short segment, skip! Sampled segment: AGCATGCGTATGCATGCGTGTGTTAGCTGTACATTGTGGCCGGCTATTGCGTATGCGCTGATCAGAGCGTTACCGCATGAGATAAGAGATTATCTTTTGTTTGCTAGTGCCCTGTGCCCTGTGCCCTCGAGTGCTCGCATGCCTCGAGCATGCGTGCTGTTAGCGCGTTTGCGCTGGTCAGAGCCCGTTCCTACCCCCAGGGGGAGTACCCCCCCAGGGGTACCTTCCTGACCGGTCGGTTA,  Segment end coordinate: 53124, relative coordinate: 52882, minimum length is: 1000
2026-10-08 14:15:31,003 - INFO - Too short segment, skip! Sampled segment: GCTGGTATCCTGCGCCC,  Segment end coordinate: 71565, relative coordinate: 71548, minimum length is: 1000
2026-10-08 14:15:31,120 - INFO - Too short segment, skip! Sampled segment: GGACTCTGTGCTGTTGTGACCTCACCGTATCAAACCATTCGGTTCTCTGTCAAGTCCTGCGATCCGCTGTTGAGTTTTGAATCTGCGAGCCGGTCGTTTCCTTCCGGCGTGACTCCATTAGACACCCATTCCCGTTCTCTGTCAAGCCCGAATTTGAAATTGCCCAAAGTCGCAGGTTGGGCAGGGTGCAGGGGGGTGCCCTACAGGGGGTCCTACAGGGGGGTGCCTACAGGGCAGGGGGTGCCAGGTGGGGTACCCGCTACCGGGGGTACTGGGTACTGGGGGTACCGGGTAGGCAGGGCAGGTGGGGGGTACCGGGTATGGGTACACCCCGCTAGGGGTGGGGGTATGCAGGGGGTAGGCAGGGCAGGGTGCAGGCAGGGGTTAGGGCAGGTAGGAGGGTGTGCAGGGGTGTAGGCAGGGCACTGCGCACAGGGTGCCGAGACGGGGTGAGGAGTGAGGGTGGAAATGGGCTCTGACCTGGGCATATGTGGGTGTCGGGGGTATGCCAGGTACCCCAGGGGGGTATGCCCTCCCCCGCCCCTTCTCGACCGGGTGGTAA,  Segment end coordinate: 50866, relative coordinate: 50304, minimum length is: 1000
2026-10-08 14:15:31,129 - INFO - Too short segment, skip! Sampled segment: TTACCCCGTTCTCTGTCCAGTCGCCCGCGAGGGCGGCTCTGAGCCTCTCCACGGGGCCTTCCTGGGCGTGTCCATCCCCATCGAAACCTGGAAACCCGTACATAATCGGGCTGCCGCA,  Segment end coordinate: 50866, relative coordinate: 50748, minimum length is: 1000
2026-10-08 14:15:31,139 - INFO - Too short segment, skip! Sampled segment: GAATTCGTTTCCGCAGGTCACAGCGTTTCTGGCTCGATGCACCCAGAACTGTGGGCCATGCCACACTCACGAGGGTTGCGGTTCTGGCGTCGCTTGTCTAGAATCGCGCGCTCCGTGCGGTTCAGGCATAGATAGGTATCCGCAGCACAGGGTGCCCTGCTGGCCGTGGGGGCCGCAGGTTACAGTAGGTGGGCAGGTAGGGCAACGGGCACAGGGTGTGGGGTATCGCACAGGCAGGCAGGGCACTGGGTGAGCAGGGCTTTCGCGTGGCAGGAGTTTGCTCGCGGGCAGGCCGGCCGGGGACTGCGCCGCAGGTGGCAGCCGGGTATGTGCGCTGGGTGTGGGTTTGCTGTGGCGTGGGTTGACAGGCACCCCCAGGGGGTGTACCCTGCCCCCGGGTCTTTCCCGACCGGGAGGTAA,  Segment end coordinate: 51241, relative coordinate: 50821, minimum length is: 1000
2026-10-08 14:15:31,140 - INFO - Too short segment, skip! Sampled segment: ACAGCGTTTCTGGCTCGATGCACCCAGAACTGTGGGCCATGCCACACTCACGAGGGTTGCGGTTCTGGCGTCGCTTGTCTAGAATCGCGCGCTCCGTGCGGTTCAGGCATAGATAGGTATCCGCAGCACAGGGTGCCCTGCTGGCCGTGGGGGCCGCAGGTTACAGTAGGTGGGCAGGTAGGGCAACGGGCACAGGGTGTGGGGTATCGCACAGGCAGGCAGGGCACTGGGTGAGCAGGGCTTTCGCGTGGCAGGAGTTTGCTCGCGGGCAGGCCGGCCGGGGACTGCGCCGCAGGTGGCAGCCGGGTATGTGCGCTGGGTGTGGGTTTGCTGTGGCGTGGGTTGACAGGCACCCCCAGGGGGTGTACCCTGCCCCCGGGTCTTTCCCGACCGGGAGGTAA,  Segment end coordinate: 51241, relative coordinate: 50840, minimum length is: 1000
2026-10-08 14:15:31,141 - INFO - Too short segment, skip! Sampled segment: CAGGGTGCCCTGCTGGCCGTGGGGGCCGCAGGTTACAGTAGGTGGGCAGGTAGGGCAACGGGCACAGGGTGTGGGGTATCGCACAGGCAGGCAGGGCACTGGGTGAGCAGGGCTTTCGCGTGGCAGGAGTTTGCTCGCGGGCAGGCCGGCCGGGGACTGCGCCGCAGGTGGCAGCCGGGTATGTGCGCTGGGTGTGGGTTTGCTGTGGCGTGGGTTGACAGGCACCCCCAGGGGGTGTACCCTGCCCCCGGGTCTTTCCCGACCGGGAGGTAA,  Segment end coordinate: 51241, relative coordinate: 50968, minimum length is: 1000
2026-10-08 14:15:31,150 - INFO - Too short segment, skip! Sampled segment: GGAGTCGTAGTGTGTGAGGCAATTCACATAGACATCTGTGGGGCTATGTGGTAGATCGAGGGTACCGGCATACCACCCTAGCTGCGAAAATCGCTCTCTGAGGCTCTCAGGGCCAGTACGGCAGGTCCTAGAGCGCCGGCTCCCTGGTGATCGACTTGGAAACCCGTAGCGGACCTTGCAGACGCA,  Segment end coordinate: 51241, relative coordinate: 51055, minimum length is: 1000
2026-10-08 14:15:31,282 - INFO - Too short segment, skip! Sampled segment: TGGTCACGGTGCCGACGTACTCCCGGCCATCCTCGGGCGAGGTGAGCCGGACCGAGTCACCGATGCGGATGATGTCCATGAGATGCCCTCTCTCTGAGTGGTTACGAATCAAGGTCGAGCGACGACCGCGTAGCCTGCGATCACCGCGAGCATCACCGGGATGAAGCTGATGATGATGAGTGCAGCGGTCATGAACTAAGTATGCACCGACCACGGTTACGAGTCAAGGGTCAATTTCGAGATGTCCATCGTCACTCGTCAAGGCCCGGTCAGACACGAAAGAACCCCTGACCCGAAGGCCAGGGGCTCAATCAGCTGGGTCGATCAGCGGAGGCTGTCGATGTGGATGCAGCCGACCTTGTCGGGGCCGAACTCGGGACTGAACCCGAGCACCTCATCCTCCTCACAAGGGAACGACGACTGATCGAACGAGATCGGATCAGCCGAAGCGATCCACGTCGGAGTCGCGATGACAGCCGGAGCTGCGATGAGGAAGAAGCCGGCTGCGATACGCTTGGTGATGGACATGACGTTCCTTTCGTCGGTGTGTTCCGTGTAAAGGCAACGCTACACCACCACCGTGGTTACGTGTCAAGCCCGAGTTTCTGCACACGGGGAGGTACCGCATATACAGGGGTGCTGTGCAGCTGGGTGTGGGTAGCAGCAGGGGGCTAGGGCACAGGGGGTAGGTGGGGTGTGGGTGTGCAGCTGGGTGTGCGCTAGGGGGGAGCGGGTAGGCAGGGTGCGGGGTACGGGCAGGGCAGGGCGTGTGCTGCGGGCAGCTGGCAGGCAGGGCTGTGCGTGTGCGGCTGCGGGTGGGCGCGCTGTGCCGGCTGTGCAGCGGCGGGTACGCCGCGGTGTGCGCACCCCCCCCCCCCCCCCCTACGGGGGCACCCCTACCCCCCGCGTGTTGACCGGATGGTAA,  Segment end coordinate: 49577, relative coordinate: 48652, minimum length is: 1000
2026-10-08 14:15:31,330 - INFO - Too short segment, skip! Sampled segment: CATGAAGCTGGGCGAGCTGGTCGAGGCGCTGGACCTACGCAAGCGGTACGCCGAGCGACACGGTGAACGTGCTCGCCTGTTCGTGTTCTCGGTCGGCAAGCTGCTGATCGTTTGGGACCGAGACAGCAAGCCATGAGCGAGGGTCGCAACACTGCACGGCGCAACAGGTTCCGGCGCTACTGGCTGCGGCGGCGCGAGGACTGCGCAGTGTGCGGCGAGCCGATCGACTACGAGGCGCATCACCTGCACCCTGACTCGTTTCAGGTCGACCACATCACGCCACTGGATGCAGGCGGCTCGGACACGCTCGACAACACGCAACCGACGCACCGCAAGTGCAACCGCGACAAGAGCAACAAGCTGCCCGACAGCGGCGGCCCGGCGCCTGCCTCAGTGGGCGTCACGTTCGTGACCGAACGCAACTGGACACCCTGACCTCAGCAAAGGGGTGGGGGGATACTCCCCGACCCCCTCCCCGGTGCACCTCGTAGGCAT,  Segment end coordinate: 60835, relative coordinate: 60340, minimum length is: 1000
2026-10-08 14:15:31,332 - INFO - Too short segment, skip! Sampled segment: TGCAACCGCGACAAGAGCAACAAGCTGCCCGACAGCGGCGGCCCGGCGCCTGCCTCAGTGGGCGTCACGTTCGTGACCGAACGCAACTGGACACCCTGACCTCAGCAAAGGGGTGGGGGGATACTCCCCGACCCCCTCCCCGGTGCACCTCGTAGGCAT,  Segment end coordinate: 60835, relative coordinate: 60676, minimum length is: 1000
2026-10-08 14:15:31,349 - INFO - Too short segment, skip! Sampled segment: AAGGCGGCATCGTGCCCGGATCCGGCAACGCCACCGATCCCAACAAGCCGCACGTCCAGGCCGACTACCAACCCTTCGAGTGGTGACCTGACCCGGATAGTTCGCGCTGATGGCCGGCGTCCCACGCAACACCGCAGTACGAGACAGGCACCGACGCGCCATCCAACGCGGACACCCGAACTGCGGTAGCGAGCACCACGACTGCGCGCAGAAGCACCCGCACTGCGGAATCTGCGGCGAACCCATCGACTACGAGCTCCCACATCTCGACCCGTGGGAGTTCGTAGTCGACCACGTTGTCCCCGTGGCAGCAGGTGGCGCCGACGAGCTCTGGAACAAGCAAGCCGCGCACCGCTACTGCAACAGCGAGAAGTCCGACCGATTGGCCGACCAGCTGCCCGTCGGAGTCACGTTCGTAACCACCCGCAGCTGGTAGCCCTCGAAAGGACAACCCAGTGACCAACCAGCCACGAGACTTGGAGTTCGCGAAGCTGCACTGGGTCCAGCCGGCCGACACCGACGAGGAACCATGACCACACGCGACCCTCGACGAGGCGCCAAGCCGCAACCCTGCAAGCACTGCGGTAAACAGATCGCCGTCGTAGCCTTCAGCCGCGACTACGTGCACATCGAAGGCGACCACGCCGGCAAGCACCGCTGCGCCATCGAGCCCTACGGTTTCCTCGCCGAGCCCGTCGGGACACCATGCCGAGCCGACGGACCGAACCCCTGCCTCGGCGCCGACCGATGAACGCCGAAACCATGTGCCAGCACCGCACCCGCCGGCGCATCCACGGCAGCATGTGGCACCACCCCGCGCCAACCGTCCCACCAGCACCCAGGCCGGGTGACCCCACCGGGCCCCCACGCCGCCACCCCATGGCAT,  Segment end coordinate: 41441, relative coordinate: 40555, minimum length is: 1000
2026-10-08 14:15:31,350 - INFO - Too short segment, skip! Sampled segment: CGCACTGCGGAATCTGCGGCGAACCCATCGACTACGAGCTCCCACATCTCGACCCGTGGGAGTTCGTAGTCGACCACGTTGTCCCCGTGGCAGCAGGTGGCGCCGACGAGCTCTGGAACAAGCAAGCCGCGCACCGCTACTGCAACAGCGAGAAGTCCGACCGATTGGCCGACCAGCTGCCCGTCGGAGTCACGTTCGTAACCACCCGCAGCTGGTAGCCCTCGAAAGGACAACCCAGTGACCAACCAGCCACGAGACTTGGAGTTCGCGAAGCTGCACTGGGTCCAGCCGGCCGACACCGACGAGGAACCATGACCACACGCGACCCTCGACGAGGCGCCAAGCCGCAACCCTGCAAGCACTGCGGTAAACAGATCGCCGTCGTAGCCTTCAGCCGCGACTACGTGCACATCGAAGGCGACCACGCCGGCAAGCACCGCTGCGCCATCGAGCCCTACGGTTTCCTCGCCGAGCCCGTCGGGACACCATGCCGAGCCGACGGACCGAACCCCTGCCTCGGCGCCGACCGATGAACGCCGAAACCATGTGCCAGCACCGCACCCGCCGGCGCATCCACGGCAGCATGTGGCACCACCCCGCGCCAACCGTCCCACCAGCACCCAGGCCGGGTGACCCCACCGGGCCCCCACGCCGCCACCCCATGGCAT,  Segment end coordinate: 41441, relative coordinate: 40773, minimum length is: 1000
2026-10-08 14:15:31,374 - INFO - Too short segment, skip! Sampled segment: CGCGGTTGGCGGAACGAGGCCCGGCGCTGGATCAGTTGCGGGGCGGCCAGTTCCAACGGCCCGGCGTCGGCTCGTCGGCCTGGCGCACGGACTCGTTGAAAAACAGCCCCGTCGGGTTGAGCACGCACAGGCTGACGACGCCACCGCCGAGCACGGCCGTGACGATCGCGGCGCGCGGCTCAGGCAGGTACTCGCCGCCAGGCGTGCCGTACGACTGGTAATGAACGATGCGGCCGACAGTCGGGGTCACAGCTCAATCTCCCGAACCGCGTACATCTTTCCGCCGTGAGCGTGCATCGCCGGGGCCAACGTGCCGAGCACACAGTCGTCGAGCGGCATCACCTCGTCGTCGACGATCACGGCGTCGAAACTGAACCCGCGGCCGTGCCCTTGCTTGATCGACGGCACGCTCATTGGAACGGTGCGAGCCACGTTCAGAGCGCGGGCGAGCCGGGCCGCGCTGTCGAGCGTGCGCGACACGACGCCGACGACCGCGCTCACGAGCCACCGCCCATCGCTGCGGCCTCCTGGCGGGCCTGCCGGGCGTTCAGCTCGACGAGCACCTCGCCAATGGCGACCAGGCAGTGCAGCGTGATCGGCGTGAGGTCGCCCTCTACCTCGGTCCACTCGTGCTTGTCGAGGGCCTCGCGCTGTGCGGCGAGGCGCTCGGTGGGCGTCATCATTCGGCGGGCCGTTCAATCTCGGCGGGCCGGTCGACCTTGCCGTCGAGGATGAAAGCGGCGATCTTGTCGGCCGCCTCGATCACCGTCAAGTCGCCGATTCCCACGCTGTCGGCCTGGCGCAGCGCGATGTGCATTGATTGCTCGCGCACCGCGCGGTCGCGCTGATCCTCGAACGCCCACACGCGGGCAGTCGGTGCGGATTCGGTCATGTCCATTGGTTGCTCCTGTGCTGGTCAGACGTGACAAAACGCCAAAATGGCTTGGAAAAAAATGCCGGGGAGAGAAAGGTGCCT,  Segment end coordinate: 59598, relative coordinate: 58622, minimum length is: 1000
2026-10-08 14:15:31,397 - INFO - Too short segment, skip! Sampled segment: CGTTCGTAACCACCCGCAGCTGGTAGCCCTCGAAAGGACAACCCAGTGACCAACCAGCCACGAGACTTGGAGTTCGCGAAGCTGCACTGGGTCCAGCCGGCCGACACCGACGAGGAACCATGACCACACGCGACCCTCGACGAGGCGCCAAGCCGCAACCCTGCAAGCACTGCGGTAAACAGATCGCCGTCGTAGCCTTCAGCCGCGACTACGTGCACATCGAAGGCGACCACGCCGGCAAGCACCGCTGCGCCATCGAGCCCTACGGTTTCCTCGCCGAGCCCGTCGGGACACCATGCCGAGCCGACGGACCGAACCCCTGCCTCGGCGCCGACCGATGAACGCCGAAACCATGTGCCAGCACCGCACCCGCCGGCGCATCCACGGCAGCATGTGGCACCACCCCGCGCCAACCGTCCCACCAGCACCCAGGCCGGGTGACCCCACCGGGCCCCCACGCCGCCACCCCATGGCAT,  Segment end coordinate: 41893, relative coordinate: 41417, minimum length is: 1000
2026-10-08 14:15:31,398 - INFO - Too short segment, skip! Sampled segment: GACCACGCCGGCAAGCACCGCTGCGCCATCGAGCCCTACGGTTTCCTCGCCGAGCCCGTCGGGACACCATGCCGAGCCGACGGACCGAACCCCTGCCTCGGCGCCGACCGATGAACGCCGAAACCATGTGCCAGCACCGCACCCGCCGGCGCATCCACGGCAGCATGTGGCACCACCCCGCGCCAACCGTCCCACCAGCACCCAGGCCGGGTGACCCCACCGGGCCCCCACGCCGCCACCCCATGGCAT,  Segment end coordinate: 41893, relative coordinate: 41644, minimum length is: 1000
2026-10-08 14:15:31,410 - INFO - Too short segment, skip! Sampled segment: GGTGCAGGGGGTCCTACAGGGGGGTCCTACAGGGGGTGCCTACAGGGCAGGGGGTGCAGGGCAGGGTGTACCTGCTACTGGGGGGTACTGGGTACTGGGGGTACCGGGTAGGCAGGGCAGGTGGGGGTACTGGGTAGGGGTACACCCCGCTAGGGGTGGGGGTATGCAGGGGTAGGGGTAGGCAGGGTGCAGGCAGGGGTTAGGGCAGGTAGGAGGGTGTGCAGGGGTGCAGGCAGGGCACTGGGCACAGGGTGCAGAGACAGGGTGCAGACGGGGTGCAGGCTCGAGGTGGAAATGGGTGCTGACCAGGGCAGATGGGGAGTCGAGGGGGTATGCCGGGTACCCCAGGGGGGTATACCCTCCCCCGCCCCTTCTCGACCGGGTGGTAA,  Segment end coordinate: 50854, relative coordinate: 50465, minimum length is: 1000
2026-10-08 14:15:31,411 - INFO - Too short segment, skip! Sampled segment: GTCCTACAGGGGGGTCCTACAGGGGGTGCCTACAGGGCAGGGGGTGCAGGGCAGGGTGTACCTGCTACTGGGGGGTACTGGGTACTGGGGGTACCGGGTAGGCAGGGCAGGTGGGGGTACTGGGTAGGGGTACACCCCGCTAGGGGTGGGGGTATGCAGGGGTAGGGGTAGGCAGGGTGCAGGCAGGGGTTAGGGCAGGTAGGAGGGTGTGCAGGGGTGCAGGCAGGGCACTGGGCACAGGGTGCAGAGACAGGGTGCAGACGGGGTGCAGGCTCGAGGTGGAAATGGGTGCTGACCAGGGCAGATGGGGAGTCGAGGGGGTATGCCGGGTACCCCAGGGGGGTATACCCTCCCCCGCCCCTTCTCGACCGGGTGGTAA,  Segment end coordinate: 50854, relative coordinate: 50475, minimum length is: 1000
2026-10-08 14:15:31,420 - INFO - Too short segment, skip! Sampled segment: CCGGTCACTGGTTGACCAAGACAACGAGACCACCTCCCTATAGGGCGGCGCGTCGGTGAGCGCCGCCGGAAGCGGCCCTGGAGGCCGCTGGATACCGGCCCTGGAGGCCGGTTCTATGTCAAGTACGACCGGCCTTCGAAGGCCGGTCTATTGGAGGGGGAGCGCTCCGGGCGCTCCCGGAGGGGAGCCGCTTGGGGGCGGCTCCTCGGAGGGCCGAGCCAGGGCGAGGCCCCATCTCTCACCCCTCCGTAGGTTCCCCTCTCTCTTCCCCCTACAACCAATAGTGGGCGACACTTTCGGATCGAGTGTCGCTGGACCCCTGGAGTGTGACAGTAGCCACATCAGTGACACTATTTCCGGGACTGTCTACCACTATCGGGTGTCTCGGCTCTGTGTGGCCCTGTGCCGGCCCGTGCCGGCGGTCGAGCCCATTACCCCGTTCTCTGTCCAGTCGCCCGCGAGGGCGGCTCTGAGCCTCTCCACGGGGCCTTCCTGGGCGTGTCCATCCCCATCGAAACCTGGAAACCCGTACATAATCGGGCTGCCGCA,  Segment end coordinate: 50854, relative coordinate: 50305, minimum length is: 1000
2026-10-08 14:15:31,421 - INFO - Too short segment, skip! Sampled segment: GGCCCTGTGCCGGCCCGTGCCGGCGGTCGAGCCCATTACCCCGTTCTCTGTCCAGTCGCCCGCGAGGGCGGCTCTGAGCCTCTCCACGGGGCCTTCCTGGGCGTGTCCATCCCCATCGAAACCTGGAAACCCGTACATAATCGGGCTGCCGCA,  Segment end coordinate: 50854, relative coordinate: 50701, minimum length is: 1000
2026-10-08 14:15:31,439 - INFO - Too short segment, skip! Sampled segment: TTGAGCAGGTCGTACGCCGGGGCGGTGTCGGTGCCCGGTACATGCTCTCGGTCAAAGCAGTCGGTGAGGTGGGCCATCATGGTCGACTTGCCCGCGCCGGGCGCGCCGATGAGGTAGATGAGGCGGTGGTTTGTGGTCATGACCAGCAT,  Segment end coordinate: 68227, relative coordinate: 68078, minimum length is: 1000
2026-10-08 14:15:31,469 - INFO - Too short segment, skip! Sampled segment: CCGATGTCCCAAGCTCAACAAGCTGCTCACTACATGCCCGATACACACATATCCCCTGCTCACACACACATGTCCTAGTGCTGTGACCAGCACAAACGCACACACACCAGTGTGCGTATGAGTTAGCTGTGCATTGTGGCCGGCACACACATACATGCAGGTAGAGCGGTTGCGAGATGAGATAAGAGATCTTGTTCTGTTTGCTAGTGCCCTGTGCCCTGTGCCCTCGAGCTGTAGAGCGTGCGATTGCACGCTCGAGGATGTGCATTTGCCCAGGTCAGAGCCCGTTTCGACCCCCCACGGGGGTACCCCCTAGGGGTACCTTCCTGACCGGTCGGTTA,  Segment end coordinate: 52561, relative coordinate: 52220, minimum length is: 1000
2026-10-08 14:15:31,526 - INFO - Too short segment, skip! Sampled segment: CAGCGGATGGACATAGCGCAGCTTGTCTGCCGGGGCGAACATCGGCATGAGCACGGTGGGATTACCGTCGGCCAGCAGCTTGGCGTACTTGCGCAGGCTGTAGATGGTGCGGTCGATATCGCCTGCTTGTGAGCGCACGCCGACCGGCTTGGTCCGGTACTCGTAGAGGTCGAACTGCTCGAAGCCGATCACGCAGCGGGGCGGCTCGATGGCGATGCCCATCTCGTCGATGTCGTCGCTGGTCGCATCGGTGCTCACCCCGTGCAGGGTCGAGCCCACCTCGCTCAGATAGATCAACCCGTCCAGGGCGATCTGCTGATGATGTGAGGACGAATGCGAGGTTTCGAAGGCGCCCTGGACCGGCTCGTGGAGCACATCCTGGGGCTGTAGTTCTTCTGTGGGCCTGACACTCATAGCCTATAGTCCTCCTGCAGTGTGGGTGTAGGGGTGTGACAGTGTGGCAACAGGACAATTGTAGTCGGTGTGCTGCACGCCAGGATTCTGATTTGTCTCGTCCTGTAGGCACGTCTCGTGCACCCACCCGATCAGGCCGATGACGAGGGCCAACACAGCGATGGCGAAGGCGGTCTGGACCCTCTGCTGACAGGGCATGGTCATCGTCCGCCGAGCCGGTTCTTGCGATTGCCGACGAGGTGATCTTTGAGGAAGCGCTGGAATCCGGCATGGATGCGCTCACCCCGCTTGGCAACCATGTCCCTGATGTCGTCCTCGGTGCAGGAGTTCTCGGCGCCGTAGGTCATCCAGGCGACAGCGACGGTCTGAGGCGAGACGCCATGATGCTCGGCCACCAGGTGTATCAGGGGCAGCAGCTCGCTCGGGATCTCGACGCGGACCGGCGGTTCGTAGCTCACAGCTCGTGCTCCTC,  Segment end coordinate: 156558, relative coordinate: 155672, minimum length is: 1000
2026-10-08 14:15:31,539 - INFO - Too short segment, skip! Sampled segment: CCCAGCCCCATCTTGCCCAGAATGTTCGCCAAAGCCGTGTACTGCTGACGATGCTCAGAGATAAGCGGATTGATAACCTCATCCCCACGCTGGTTATACGACAACAGCCGACCGTCAATCTCGGTATCAAGCTGATCCAGCCTGTCCGCAATGCGACACGCATTGACTAAAAGCACTCGGCTCGCAGCGTCAAGTTCCCTATCGGCAGTAATGCTCGTCCACAGCGTGGTACCGGCCTCCATGAGACCCGGCGGAACCGGACTTTTACCTGGTAACCGCTTACGTGGCGGCATAAATCCCCCCTTATCAACGATCCGTCAGCTCCCGGTACTTACGGCCCATTTCCTCAGCTATAACGTTCGCCTCTTCGCGCATCGTGTAATCCCTAGCCTCTTGAATAGTCGCCCGCTCCCACGAACTGCGCCCCGACTTATCCATTCGCGCAAGAAACTCCATAATCGCCTCATCCTCACTAGTCGATTGAGACCGTGAAGCGTCACGCATCAACCGCCAAAAGTCCGGACTCCACCCATCAGGCACCCTTTCGGCCTTCCGCTCCTCGAAAGCCTCCCTAGTGGCCTTCCGAGAGTCCCGACCCCGCTTACCAGTCGGGTTGTTGTCACCACCACGCTTGCCCATGCGCTGAAACCCCCTTAAGTGGGTGCGACCAGCGGTTTTGTCGCACTTTCCTGGCCTTTTAACGGCCCTAGCTCGGCAGAGAGAGAAATGTCGCT,  Segment end coordinate: 76271, relative coordinate: 75537, minimum length is: 1000
2026-10-08 14:15:31,560 - INFO - Too short segment, skip! Sampled segment: CGTAGCCCTTGAAGTAGTGGTAGCTGACCAGGATGTTTCGCGGTGCTGGGATCACGGTGCGCCTGCGGTGTCCAGGAGCGCCGCCAGGGCGTCGGTGTCGTCGGGGTAGTTGGAGCGCCAGGCCGTCCACCGGCGGCTGACCTCGGGGCCGAGGATCAGGCGCACGCTGTCGTGCGCGTCGGTGTCCTTGGGGTCGCCGTGCTCGTCGGCCAGGTCGTCCAGGTCAGGCGGCCCGGAGGTCAGCTCGACCAGCATCTGCACGTAGTCCTCGTCAAAGCCGGTGCCCTCCAGGCCTTTCGCCGGGTCCAGGCCTTGCAGCAGCTCCAGGAGCGTGTCGTTGTCGGTGCTGCCGACCTCGCTGGCCCGGTTGTCCACGGCCACGATGCGCGCAGCGGTGTCCTCGTCCACGTCGACCCAGTGCACCAGGATTTCCCCGTACGCGGGGCCGTCGGTCTCGGCCAGGTCGCGCATGGCCATCAGGGTGTGGTTGCCCGCCAACACCTCGTTGGGCCGCCCGGTCTTGGTCCCGATGTTGGCACAGATCGGTTTGTACTGGCCATGCGTGCGCAGGCTGTTGGCGATCAGCTCGGTGTTACCGCGCCGGGGGTTCTTGTAGTAGGTGCTCAGCGTTGCCAGGGCCACCTTGGTGGTGGTCCCGACCAACCCGGTCACCGGTTCGACCGGCGTTTCCGGGCTGGCGTCGCTGAACACGGGTGCAGGTGTTGCGCCGGGCGAGCTGCCAAACGGCGATGACTTGGTCGAGGCCATGTCGAGCAGCTTAGGACAATGCCGCGCATACCACGTTGCGGCGCGGAAATCTCCCCGGAGACAACACGTGCGCAC,  Segment end coordinate: 67436, relative coordinate: 66593, minimum length is: 1000
2026-10-08 14:15:31,561 - INFO - Too short segment, skip! Sampled segment: CGGTCTCGGCCAGGTCGCGCATGGCCATCAGGGTGTGGTTGCCCGCCAACACCTCGTTGGGCCGCCCGGTCTTGGTCCCGATGTTGGCACAGATCGGTTTGTACTGGCCATGCGTGCGCAGGCTGTTGGCGATCAGCTCGGTGTTACCGCGCCGGGGGTTCTTGTAGTAGGTGCTCAGCGTTGCCAGGGCCACCTTGGTGGTGGTCCCGACCAACCCGGTCACCGGTTCGACCGGCGTTTCCGGGCTGGCGTCGCTGAACACGGGTGCAGGTGTTGCGCCGGGCGAGCTGCCAAACGGCGATGACTTGGTCGAGGCCATGTCGAGCAGCTTAGGACAATGCCGCGCATACCACGTTGCGGCGCGGAAATCTCCCCGGAGACAACACGTGCGCAC,  Segment end coordinate: 67436, relative coordinate: 67042, minimum length is: 1000
2026-10-08 14:15:31,602 - INFO - Too short segment, skip! Sampled segment: GATACCGATCTGCGGTTGCTTCACCGGCCCACGCGCTGGGAGCTTCGTGACCGGGTTGTCTGTCTTGTTGCGTCGGACGCGCTGATCCGATCGCTTACCGATAGGGCCTCTTTCGCCCACTTGACACCTCCTGGGTGAAAAGCGGGCACCTGGCCCGCTACCGAGAGCCGGGATGGCGCTCGATAGGTCGCCTCCTCATTGCTCGTAACTGCCGCTTGCGGGCGTGGCCTTCTGCGGATGACTTTCTGCCGTGGCAGCGGTTGCACGCTGCCTGGAGATTGCGGCGACTGTGGTCGTCGCCGCGCCTGATGTGGTCAACATCGGTTGCCTTCCTGAGGCAACCGGGACCCTGAATCTGACACTGGTAGCCCGCTGCTTCGAGCACGGGCTGCCGGTAGTTCTCTTCCCAGTCGGCGGGAAGCCGGCTGGCGCGGTCGGAGGAGCTCCAGCTCCTCCTCGCATCTGAGGGTGAAATTTGAGTACCTCCCTAGTAGAGGCAGCCGCCTGTGGGCGGCGGCTGCCGACAGGGAGAAGACCGACTGAGAAGGAGGTCTTCGACCTCTACCAACGGGACCGCTCTGAGGCGGTCCCTTGTACTATGTCTAGTCGGCCCGCGCCGATTCGCGGGCCTCTCTTACTTACCCGAGCGCCCTGCGGGGCGCTCCCTGTCGGCAGCGGCCGTGTGGGGGTGAAGGCCGCTGCCTCCTGGGGCGGCGCTGAACGCCGCTACTCAACCCCCTCCTTAGAGGTTCCCCCTTACGTTGGGCCTCTACCCTGTACATACCTTCCTATTCCGCGTGTGAGATGACAAGTGTGGCGCGGATCACCGCGCATGGAACGTCGACCTGGGCTTTTCCCTCGCGTGCCTGGCGGGACTCCTGTGACTCAAATCTGAAAACCCGTACATGATCGGCCAGGCGCA,  Segment end coordinate: 51500, relative coordinate: 50578, minimum length is: 1000
2026-10-08 14:15:31,610 - INFO - Too short segment, skip! Sampled segment: TCCTGCTGGACGAACACGACATTGACGACATGGACGGGTTCCGCCGGAATAAGTACCTTGACGACGTGGCCGAAAGGGTGGGCAAGACCTTGGAAACCAAGCTCAAGGCCATTGACCGGCTGGTGAACGTTGGCGCGAGGGCTGGCAAGATTCTGGGCTACGACGCGCCCACCAAGCTTGAGGGTAACGGCATGGGCGGTGACATTACGGTGACGTTCGCCCCGGCCATGAACAAGCCAGCCGAAATGGCGGAACCGGAAATGATCATTGAGCCGGAACAGTAAGCGCAAGGGCCGGGTTGTCACGTACAACTACGCCCCGCACGAGGGACCGCAAAGCCTTGCCCACCAA,  Segment end coordinate: 71200, relative coordinate: 70849, minimum length is: 1000
2026-10-08 14:15:31,618 - INFO - Too short segment, skip! Sampled segment: GACGGCGGCGAACGGCGCCCCGAACCCGTAGTCGACGGCCACAACGCGCGGGTAGGTGACCAAATCCATGGGGGAAATGTCCGGCTCAACAACATGGATGCTGTCCCGCCATTGGGCGAACCGCACGCCGTCCAGGACGTTCCAGTCTCCATCACGCAGCGCCTTGCGTAGGTTGTCCGGCAGGGCGTTGAGCTTGTCAATGTAGGCGCCGTCAATACTGGGGTTGTCCGTGGCCTTGGCCGGGATATAGCAGCGGGTGCCGGGGTTGGGGTCGTCCAGCGTGGCAGCCATTTTGAACACCTTGGTTGCCGGGGCCGGGTCCACAAAGCGAGCCTTCACAAAGTGGTGCCCGGGTCCGCCGGGGTTGGCGGTGGAAACCACGCCCGTGCGCAGCCCCAACGCTTCCATGCGTTCTTTGACCTCGCCAGCGGAACGCAGACGGGAAAGCATATAGGTGTATTGCTTTTCGGTGAAGTGGGTCAATTCCTCAAAGCCAATGCGCTGGTATTCCGCGCCCTGATACTTGAGCAAGTCCGATTCGTTGCGTAGGTGGCCCAATTCCAGCACGCTGCCGTTGGCGAACCTCCACATGTGTTCGGAACGGTTGTACTTGCCCAAACCAACCGGGGTTTCCTCCAGCAGCGGGTCAATGACCGAACGCGCAAGGTCCGGGAACGTTCGGCGGAAGATAATAGCGCGACCACCGGGCACTTGCATGCAGAATTGGAAGAAATCGGCGCGCATGAACCGCGACTTGCCGCCGCCGGCGGCTCCCCCGTAGAGCAGTTCGTCCACCTTCAT,  Segment end coordinate: 71200, relative coordinate: 70399, minimum length is: 1000
2026-10-08 14:15:31,651 - INFO - Too short segment, skip! Sampled segment: TCCTGTAGGCACGTCTCGTGCACCCACCCGATCAGGCCGATGACGAGGGCCAACACAACGATGGCGAAGGCGATCTGGACCTTCTGCTGACAGGACATGGTCATCGTCCGCCGAGCCAGTTCTTGCGATTGCCGACGAGGTGATCTTTGAGGAAGCGCTGGAATCCGGCATGGATGCGCTCACCCTGCTTGGCAGCCATGTCCCTGATGTCGTCCTCGGTGCAGGCGTTCTCGGCGCCGTAGGTCATCCAGGCGACAGCGATGGCCTGAGGCGAGACGCCATGATGCTCGGCCACCAGGTGTATCAGGGGCAGCAGCTCGCTCGGGATCTCGACGCGGACCGGCGGTTCGTAGCTCACAGCTCGTGCTCCTC,  Segment end coordinate: 154872, relative coordinate: 154500, minimum length is: 1000

In [24]:
raw_segment_train_df.head()

,segment_id,sequence_id,segment_start,segment_end,segment
0,0,0,249,2249,CGCAGCAGGTACTTCATGAGCCTTTCCTTCGGTCGCCGTCTGCAGC...
1,1,0,1766,3766,CCTCAAGGACCGCATCGCGCAGATGGACGCGGGCTTCGAGTTCGCA...
2,2,0,1788,3788,ATGGACGCGGGCTTCGAGTTCGCACCCGAGATCCCCGAGACGATCT...
3,3,0,4773,6773,GGCGCGTTCACCAACGACCCGAAGCGATCGACTGACTGCTCTGGCC...
4,4,0,5206,7206,ACGCCCCGGCCGCGCCGGGTGAGATGACGGTCCCGCTGTTCCAGAA...

In [25]:
labels = train_dataset.set_index("sequence_id")["label"]
assert labels.index.is_unique, "sequence_id is not unique in test_dataset"

raw_segment_train_df["label"] = raw_segment_train_df["sequence_id"].map(labels)
assert raw_segment_train_df["label"].notna().all(), "some segments have a sequence_id missing from test_dataset"

In [26]:
raw_segment_train_df.head()

,segment_id,sequence_id,segment_start,segment_end,segment,label
0,0,0,249,2249,CGCAGCAGGTACTTCATGAGCCTTTCCTTCGGTCGCCGTCTGCAGC...,0
1,1,0,1766,3766,CCTCAAGGACCGCATCGCGCAGATGGACGCGGGCTTCGAGTTCGCA...,0
2,2,0,1788,3788,ATGGACGCGGGCTTCGAGTTCGCACCCGAGATCCCCGAGACGATCT...,0
3,3,0,4773,6773,GGCGCGTTCACCAACGACCCGAAGCGATCGACTGACTGCTCTGGCC...,0
4,4,0,5206,7206,ACGCCCCGGCCGCGCCGGGTGAGATGACGGTCCCGCTGTTCCAGAA...,0

In [27]:
segmentation_params = {
    "max_length": 2_000,
    "min_length": int(2_000 * 0.5),
    "type": "contiguous",
}

raw_segment_test_df = segment_sequences(test_dataset, segmentation_params, AsDataFrame=True)

2026-10-08 14:15:42,488 - INFO - Checking input DataFrame!
2026-10-08 14:15:42,489 - INFO - Checking input sequence_id is valid primary key in the DataFrame

In [28]:
raw_segment_test_df.head()

,segment_id,sequence_id,segment_start,segment_end,segment
0,0,0,0,2000,AATTTTCCTTATTAGGCCGCAAGGGCCTTCATAGTTTTAGCGATTT...
1,1,0,2000,4000,TTCAGGATTTCCATTAAGTGCATGAGCATCAATCATGTTAGTAATC...
2,2,0,4000,6000,TTGAGAACTTTACCACGCAATGGATAACCACCGTGAAGTTCTTTAT...
3,3,0,6000,8000,CACTTCATCAAAGAACCCAGCTTCGTTAGTAGAGAGCCAGATAAAG...
4,4,0,8000,10000,AAATTAGGTCTGTCATAACCTACATGTAATAACCACTCTTCACTCC...

In [29]:
labels = test_dataset.set_index("sequence_id")["label"]
assert labels.index.is_unique, "sequence_id is not unique in test_dataset"

raw_segment_test_df["label"] = raw_segment_test_df["sequence_id"].map(labels)
assert raw_segment_test_df["label"].notna().all(), "some segments have a sequence_id missing from test_dataset"

In [30]:
raw_segment_test_df.head()

,segment_id,sequence_id,segment_start,segment_end,segment,label
0,0,0,0,2000,AATTTTCCTTATTAGGCCGCAAGGGCCTTCATAGTTTTAGCGATTT...,1
1,1,0,2000,4000,TTCAGGATTTCCATTAAGTGCATGAGCATCAATCATGTTAGTAATC...,1
2,2,0,4000,6000,TTGAGAACTTTACCACGCAATGGATAACCACCGTGAAGTTCTTTAT...,1
3,3,0,6000,8000,CACTTCATCAAAGAACCCAGCTTCGTTAGTAGAGAGCCAGATAAAG...,1
4,4,0,8000,10000,AAATTAGGTCTGTCATAACCTACATGTAATAACCACTCTTCACTCC...,1

In [31]:
hf_train_dataset = datasets.Dataset.from_pandas(raw_segment_train_df)
hf_test_dataset = datasets.Dataset.from_pandas(raw_segment_test_df)

In [4]:
model_path = 'neuralbioinfo/prokbert-mini-long'

# model = ProkBertForSequenceClassification.from_pretrained(model_path, trust_remote_code=True)
model = ProkBertForSequenceClassification.from_pretrained(
    model_path,
    trust_remote_code=True,
    hidden_dropout_prob=0.0,            # dropout az enkóder rejtett rétegeiben
    attention_probs_dropout_prob=0.0,   # dropout az attention súlyokon
    classifier_dropout=0.1,             # a fej dropoutja maradjon, ahogy eddig
)
tokenizer = LCATokenizer.from_pretrained(model_path, trust_remote_code=True)

data_collator = DataCollatorWithPadding(tokenizer=tokenizer)

2026-10-21 15:01:57,829 - INFO - HTTP Request: HEAD https://huggingface.co/neuralbioinfo/prokbert-mini-long/resolve/main/config.json "HTTP/1.1 307 Temporary Redirect"
2026-10-21 15:01:57,862 - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/neuralbioinfo/prokbert-mini-long/93fa164b6b8f7a641c5aa1be59e03a071c6a44bb/config.json "HTTP/1.1 200 OK"
2026-10-21 15:01:58,461 - INFO - HTTP Request: HEAD https://huggingface.co/neuralbioinfo/prokbert-mini-long/resolve/main/model.safetensors "HTTP/1.1 302 Found"
2026-10-21 15:01:58,611 - INFO - HTTP Request: HEAD https://huggingface.co/neuralbioinfo/prokbert-mini-long/resolve/main/tokenizer_config.json "HTTP/1.1 307 Temporary Redirect"
2026-10-21 15:01:58,643 - INFO - HTTP Request: HEAD https://huggingface.co/api/resolve-cache/models/neuralbioinfo/prokbert-mini-long/93fa164b6b8f7a641c5aa1be59e03a071c6a44bb/tokenizer_config.json "HTTP/1.1 200 OK"
2026-10-21 15:01:58,772 - INFO - HTTP Request: GET https://huggingface.co/api/models/neuralbioinfo/prokbert-mini-long/tree/main/additional_chat_templates?recursive=false&expand=false "HTTP/1.1 404 Not Found"
2026-10-21 15:01:58,900 - INFO - HTTP Request: GET https://huggingface.co/api/models/neuralbioinfo/prokbert-mini-long/tree/main?recursive=true&expand=false "HTTP/1.1 200 OK"

In [5]:
print(model.config.hidden_dropout_prob, model.config.attention_probs_dropout_prob)   # 0.0 0.0 legyen

0.0 0.0

In [34]:
trainable = sum(p.numel() for p in model.parameters() if p.requires_grad)
total = sum(p.numel() for p in model.parameters())
print(f"trainable: {trainable:,} / {total:,} ({trainable / total:.2%})")

trainable: 26,433,027 / 26,433,027 (100.00%)

In [ ]:
# comment if you want to freeze the BERT layers
for param in model.bert.parameters():
    param.requires_grad = False

# comment if you want to freeze the weighting layer (-> mean pooling)
for p in model.weighting_layer.parameters():
    p.requires_grad_(False)

trainable = sum(p.numel() for p in model.parameters() if p.requires_grad)
total = sum(p.numel() for p in model.parameters())
print(f"trainable: {trainable:,} / {total:,} ({trainable / total:.2%})")

trainable: 1,155 / 26,433,027 (0.00%)

In [36]:
max_length=512

def _tokenize_fn(batch):
    tokenized = tokenizer(
        batch["segment"],
        padding="longest",
        truncation=True,
        max_length=max_length,
    )
    # Zero out first/last attention token
    masks = tokenized["attention_mask"]
    for m in masks:
        m[0] = 0
        m[-1] = 0
    return {
        "input_ids": tokenized["input_ids"],
        "attention_mask": masks,
        "labels": batch["label"]
    }

In [37]:
tokenized_train_ds = hf_train_dataset.map(
    _tokenize_fn,
    batched=True,
    num_proc=num_cores,
    remove_columns=hf_train_dataset.column_names,
    keep_in_memory=True,
)
tokenized_test_ds = hf_test_dataset.map(
    _tokenize_fn,
    batched=True,
    num_proc=num_cores,
    remove_columns=hf_test_dataset.column_names,
    keep_in_memory=True,
)

Map (num_proc=8):   0%|          | 0/57446 [00:00<?, ? examples/s]

Map (num_proc=8):   0%|          | 0/12420 [00:00<?, ? examples/s]

In [38]:
# tokenized_train_ds

In [39]:
def compute_metrics(eval_pred):
    logits, labels = eval_pred
    if isinstance(logits, tuple):   # some models also return hidden states
        logits = logits[0]
    preds = logits.argmax(axis=-1)
    return {
        "accuracy": accuracy_score(labels, preds),
        "balanced_accuracy": balanced_accuracy_score(labels, preds),
        "f1": f1_score(labels, preds, average="macro"),
        "mcc": matthews_corrcoef(labels, preds),
    }

In [ ]:
training_args = TrainingArguments(
    output_dir=f"{base_dir}/phastyle-sequence-db-embedding-v0-compare",
    max_steps=20_000,
    per_device_train_batch_size=batch_size,
    per_device_eval_batch_size=batch_size * 4,
    learning_rate=1e-3,
    warmup_steps=0.1,
    weight_decay=0.01,
    eval_strategy="steps",
    eval_steps=200,
    save_steps=200,
    logging_steps=50,
    save_total_limit=2,
    load_best_model_at_end=True,
    metric_for_best_model="balanced_accuracy",
    dataloader_num_workers=4,
    remove_unused_columns=False,
    fp16=torch.cuda.is_available(),
    report_to="wandb",
    run_name="phastyle-sequence-db-embedding-v0-compare",
    seed=42,
)

In [43]:
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_train_ds,
    eval_dataset=tokenized_test_ds,
    data_collator=data_collator,
    compute_metrics=compute_metrics,
)

In [ ]:
trainer.train()

In [ ]:
# srun --job-name=phastyle-sequence-db-embedding-v0-compare-head \
#      --nodes=1 \
#      --nodelist=lolka \
#      --ntasks-per-node=1 \
#      --cpus-per-task=8 \
#      --gres=gpu:2 \
#      --mem=150G \
#      --time=7-00:00:00 \
#      --partition=hi \
#      --output=/home/osvathm/prokbert/logs/%x_%j.out \
#      --error=/home/osvathm/prokbert/logs/%x_%j.err \
#      torchrun --nproc_per_node=2 examples/phastyle_training_compare_head.py

# notes
# requested gpu count should match nproc_per_node param